apps:
  installkernel-wsl:
    command: 'bin/installkernel-wsl'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/installkernel-wsl/issues'
description: 'Script and installkernel hook to copy Linux kernel to the host system and update .wslconfig.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/installkernel-wsl/issues'
license: 'MIT'
name: 'installkernel-wsl'
parts:
  installkernel-wsl:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/installkernel-wsl'
summary: 'Script and installkernel hook to copy Linux kernel to the host system and update .wslconfig.'
title: 'installkernel-wsl'
version: '0.0.4'
website: 'https://tatsh.github.io/installkernel-wsl/'
